config/routes.rb
OpenResRails::Application.routes.draw do
  devise_for :users

  root to: 'home#index'

  get '/dashboard' => 'users#dashboard', as: :dashboard
  get '/users' => 'users#index', as: :users

  get '/about' => 'home#about'

  resources :functions

  resources :sectors

  resources :room_types

  resources :places

  resources :object_resources

  resources :services

  post 'reservations/approve/:id' => 'reservations#approve', as: :approve
  post 'reservations/pending/:id' => 'reservations#pending', as: :pending
  post 'reservations/reject/:id' => 'reservations#reject', as: :reject

  resources :reservations, except: [:edit, :update]

  resources :users, except: [:new, :create]

end

app/models/function.rb
# -*- encoding : utf-8 -*-
class Function < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :description, :name

  has_many :users
  has_many :permissions
end

app/controllers/functions_controller.rb
# -*- encoding : utf-8 -*-
class FunctionsController < ApplicationController
  # GET /functions
  # GET /functions.json
  def index
    @functions = Function.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @functions }
    end
  end

  # GET /functions/1
  # GET /functions/1.json
  def show
    @function = Function.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @function }
    end
  end

  # GET /functions/new
  # GET /functions/new.json
  def new
    @function = Function.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @function }
    end
  end

  # GET /functions/1/edit
  def edit
    @function = Function.find(params[:id])
  end

  # POST /functions
  # POST /functions.json
  def create
    @function = Function.new(params[:function])

    respond_to do |format|
      if @function.save
        format.html { redirect_to @function, notice: 'Function was successfully created.' }
        format.json { render json: @function, status: :created, location: @function }
      else
        format.html { render action: "new" }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /functions/1
  # PUT /functions/1.json
  def update
    @function = Function.find(params[:id])

    respond_to do |format|
      if @function.update_attributes(params[:function])
        format.html { redirect_to @function, notice: 'Function was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /functions/1
  # DELETE /functions/1.json
  def destroy
    @function = Function.find(params[:id])
    @function.destroy

    respond_to do |format|
      format.html { redirect_to functions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/functions_helper.rb
# -*- encoding : utf-8 -*-
module FunctionsHelper
end

app/views/functions/_form.html.erb
<%= simple_form_for @function, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                functions_path, :class => 'btn' %>
  </div>
<% end %>

app/views/functions/_functions_table.html.erb
<%- model_class = Function -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% functions.each do |function| %>
      <tr>
        <td><%= link_to function.id, function_path(function) %></td>
        <td><%= function.name %></td>
        <td><%= function.description %></td>
        <td><%=l function.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_function_path(function), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      function_path(function),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/functions/edit.html.erb
<%- model_class = Function -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/functions/index.html.erb
<%- model_class = Function -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= render "functions_table", functions: @functions %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_function_path,
            :class => 'btn btn-primary' %>

app/views/functions/new.html.erb
<%- model_class = Function -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/functions/show.html.erb
<%- model_class = Function -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @function.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @function.description %></dd>
</dl>

<h3>Usuários com esta função</h3>

<%= render "users/users_table", users: @function.users %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              functions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_function_path(@function), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              function_path(@function),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>