config/routes.rb
OpenResRails::Application.routes.draw do
  devise_for :users

  root to: 'home#index'

  get '/dashboard' => 'users#dashboard', as: :dashboard
  get '/users' => 'users#index', as: :users

  get '/about' => 'home#about'

  resources :functions

  resources :sectors

  resources :room_types

  resources :places

  resources :object_resources

  resources :services

  post 'reservations/approve/:id' => 'reservations#approve', as: :approve
  post 'reservations/pending/:id' => 'reservations#pending', as: :pending
  post 'reservations/reject/:id' => 'reservations#reject', as: :reject

  resources :reservations, except: [:edit, :update]

  resources :users, except: [:new, :create]

end

app/models/ability.rb
# -*- encoding : utf-8 -*-
class Ability
  include CanCan::Ability

  def initialize(user)
    user.function.permissions.each do |permission|
      if permission.subject_id.nil?
        can permission.action.to_sym, permission.subject_class.constantize
      else
        can permission.action.to_sym, permission.subject_class.constantize, :id => permission.subject_id
      end
    end
  end
end

app/models/function.rb
# -*- encoding : utf-8 -*-
class Function < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :description, :name

  has_many :users
  has_many :permissions
end

app/models/object_resource.rb
# -*- encoding : utf-8 -*-
class ObjectResource < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates_presence_of :sector_id
  validates_presence_of :tombamento
  validates_presence_of :name
  
  attr_accessible :description, :name, :tombamento, :sector_id, :place_id, :category_list

  acts_as_taggable_on :categories

  belongs_to :sector
  belongs_to :place
  has_and_belongs_to_many :reservations
end

app/models/permission.rb
# -*- encoding : utf-8 -*-
class Permission < ActiveRecord::Base
  attr_accessible :action, :subject_class, :subject_id

  belongs_to :function
end

app/models/place.rb
# -*- encoding : utf-8 -*-
class Place < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  validates_presence_of :sector_id
  validates_presence_of :room_type_id
  validates_presence_of :code
  validates_presence_of :name

  attr_accessible :capacity, :code, :description, :length, :name, :width, :sector_id,
                  :room_type_id, :service_ids

  belongs_to :sector
  belongs_to :room_type
  has_many :reservations
  has_many :object_resources
  has_and_belongs_to_many :services
end

app/models/reservation.rb
# -*- encoding : utf-8 -*-
class Reservation < ActiveRecord::Base
  attr_accessible :begin, :end, :status, :place_id, :object_resource_ids

  validates_inclusion_of :status, :in => %w(Pending Approved Rejected)

  belongs_to :user
  belongs_to :place
  has_and_belongs_to_many :object_resources

  def self.approve(reservation)
    reservation.status = "Approved"

    Reservation.all.each do |reser|
      if reservations_collide?(reservation, reser)
        return false
      end
    end

    return reservation.save
  end

  def self.reservations_collide?(reservation, reser)
    return false if reser == reservation or reser.status != "Approved"

    needs_check = false

    needs_check = true if reservation.place == reser.place and 
      not (reservation.place.nil? or reser.place.nil? ) or 
      not (reservation.object_resources & reser.object_resources).empty?
      
    return true if needs_check and
      reser.begin <= reservation.end and reservation.begin <= reser.end  

    return false 
  end

  def self.reject(reservation)
    reservation.status = "Rejected"
    return reservation.save
  end

  def self.set_pending(reservation)
    reservation.status = "Pending"
    return reservation.save
  end
end

app/models/room_type.rb
# -*- encoding : utf-8 -*-
class RoomType < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  attr_accessible :description, :name

  has_many :places
end

app/models/sector.rb
# -*- encoding : utf-8 -*-
class Sector < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  attr_accessible :description, :name

  has_many :users
  has_many :places
  has_many :object_resources
end

app/models/service.rb
# -*- encoding : utf-8 -*-
class Service < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  attr_accessible :description, :name

  has_and_belongs_to_many :places
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :cpf, :name

  belongs_to :function
  belongs_to :sector

  has_many :reservations
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/object_resources_controller.rb
# -*- encoding : utf-8 -*-
class ObjectResourcesController < ApplicationController
  # GET /object_resources
  # GET /object_resources.json
  def index
    @object_resources = ObjectResource.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @object_resources }
    end
  end

  # GET /object_resources/1
  # GET /object_resources/1.json
  def show
    @object_resource = ObjectResource.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @object_resource }
    end
  end

  # GET /object_resources/new
  # GET /object_resources/new.json
  def new
    @object_resource = ObjectResource.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @object_resource }
    end
  end

  # GET /object_resources/1/edit
  def edit
    @object_resource = ObjectResource.find(params[:id])
  end

  # POST /object_resources
  # POST /object_resources.json
  def create
    @object_resource = ObjectResource.new(params[:object_resource])

    respond_to do |format|
      if @object_resource.save
        format.html { redirect_to @object_resource, notice: 'Object resource was successfully created.' }
        format.json { render json: @object_resource, status: :created, location: @object_resource }
      else
        format.html { render action: "new" }
        format.json { render json: @object_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /object_resources/1
  # PUT /object_resources/1.json
  def update
    @object_resource = ObjectResource.find(params[:id])

    respond_to do |format|
      if @object_resource.update_attributes(params[:object_resource])
        format.html { redirect_to @object_resource, notice: 'Object resource was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @object_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /object_resources/1
  # DELETE /object_resources/1.json
  def destroy
    @object_resource = ObjectResource.find(params[:id])
    @object_resource.destroy

    respond_to do |format|
      format.html { redirect_to object_resources_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  def index
  end

  def dashboard
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/functions_helper.rb
# -*- encoding : utf-8 -*-
module FunctionsHelper
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/helpers/object_resources_helper.rb
# -*- encoding : utf-8 -*-
module ObjectResourcesHelper
end

app/helpers/places_helper.rb
# -*- encoding : utf-8 -*-
module PlacesHelper
end

app/helpers/reservations_helper.rb
# -*- encoding : utf-8 -*-
module ReservationsHelper
end

app/helpers/room_types_helper.rb
# -*- encoding : utf-8 -*-
module RoomTypesHelper
end

app/helpers/sectors_helper.rb
# -*- encoding : utf-8 -*-
module SectorsHelper
end

app/helpers/services_helper.rb
# -*- encoding : utf-8 -*-
module ServicesHelper
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/object_resources/_form.html.erb
<%= simple_form_for @object_resource, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :tombamento %>
  <%= f.input :description %>
  <%= f.input :category_list %>

  <%= f.association :sector %>
  <%= f.association :place %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                object_resources_path, :class => 'btn' %>
  </div>
<% end %>

app/views/object_resources/_object_resources_table.html.erb
<%- model_class = ObjectResource -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:tombamento) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% object_resources.each do |object_resource| %>
      <tr>
        <td><%= link_to object_resource.id, object_resource_path(object_resource) %></td>
        <td><%= object_resource.name %></td>
        <td><%= object_resource.description %></td>
        <td><%= object_resource.tombamento %></td>
        <td><%=l object_resource.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_object_resource_path(object_resource), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      object_resource_path(object_resource),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/object_resources/edit.html.erb
<%- model_class = ObjectResource -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/object_resources/index.html.erb
<%- model_class = ObjectResource -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= render "object_resources_table", object_resources: @object_resources %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_object_resource_path,
            :class => 'btn btn-primary' %>

app/views/object_resources/new.html.erb
<%- model_class = ObjectResource -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/object_resources/show.html.erb
<%- model_class = ObjectResource -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @object_resource.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @object_resource.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tombamento) %>:</strong></dt>
  <dd><%= @object_resource.tombamento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:categories) %>:</strong></dt>
  <dd><%= @object_resource.category_list %></dd>
  <dt><strong><%= model_class.human_attribute_name(:place) %>:</strong></dt>

  <% if @object_resource.place %>
    <dd><%= @object_resource.place.name %></dd>
  <% else %>
    <dd>Nenhum</dd>
  <% end %>
</dl>

<h3>Reservas associadas a este objeto</h3>

<%= render "reservations/reservations_table", reservations: @object_resource.reservations %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              object_resources_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_object_resource_path(@object_resource), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              object_resource_path(@object_resource),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>