config/routes.rb
OpenResRails::Application.routes.draw do
  devise_for :users

  root to: 'home#index'

  get '/dashboard' => 'users#dashboard', as: :dashboard
  get '/users' => 'users#index', as: :users

  get '/about' => 'home#about'

  resources :functions

  resources :sectors

  resources :room_types

  resources :places

  resources :object_resources

  resources :services

  post 'reservations/approve/:id' => 'reservations#approve', as: :approve
  post 'reservations/pending/:id' => 'reservations#pending', as: :pending
  post 'reservations/reject/:id' => 'reservations#reject', as: :reject

  resources :reservations, except: [:edit, :update]

  resources :users, except: [:new, :create]

end

app/models/place.rb
# -*- encoding : utf-8 -*-
class Place < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  validates_presence_of :sector_id
  validates_presence_of :room_type_id
  validates_presence_of :code
  validates_presence_of :name

  attr_accessible :capacity, :code, :description, :length, :name, :width, :sector_id,
                  :room_type_id, :service_ids

  belongs_to :sector
  belongs_to :room_type
  has_many :reservations
  has_many :object_resources
  has_and_belongs_to_many :services
end

app/controllers/places_controller.rb
# -*- encoding : utf-8 -*-
class PlacesController < ApplicationController
  # GET /places
  # GET /places.json
  def index
    @places = Place.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @places }
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/places_helper.rb
# -*- encoding : utf-8 -*-
module PlacesHelper
end

app/views/places/_form.html.erb
<%= simple_form_for @place, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :code %>
  <%= f.input :capacity %>
  <%= f.input :width %>
  <%= f.input :length %>

  <%= f.association :sector %>
  <%= f.association :room_type %>

  <%= f.association :services, as: :check_boxes %>

  <%= f.input :description %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                places_path, :class => 'btn' %>
  </div>
<% end %>

app/views/places/_places_table.html.erb
<%- model_class = Place -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:capacity) %></th>
      <th><%= model_class.human_attribute_name(:width) %></th>
      <th><%= model_class.human_attribute_name(:length) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% places.each do |place| %>
      <tr>
        <td><%= link_to place.id, place_path(place) %></td>
        <td><%= place.name %></td>
        <td><%= place.description %></td>
        <td><%= place.code %></td>
        <td><%= place.capacity %></td>
        <td><%= place.width %></td>
        <td><%= place.length %></td>
        <td><%=l place.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_place_path(place), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      place_path(place),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/places/edit.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/places/index.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= render "places_table", places: @places %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_place_path,
            :class => 'btn btn-primary' %>

app/views/places/new.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/places/show.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @place.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @place.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @place.code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:capacity) %>:</strong></dt>
  <dd><%= @place.capacity %></dd>
  <dt><strong><%= model_class.human_attribute_name(:width) %>:</strong></dt>
  <dd><%= @place.width %></dd>
  <dt><strong><%= model_class.human_attribute_name(:length) %>:</strong></dt>
  <dd><%= @place.length %></dd>

  <!-- setor eh obrigatorio -->
  <dt><strong><%= model_class.human_attribute_name(:sector) %>:</strong></dt>
  <dd><%= @place.sector.name %></dd>
</dl>

<h3>Serviços disponíveis neste lugar</h3>

<%= render "services/services_table", services: @place.services %>

<h3>Reservas associadas a este lugar</h3>

<%= render "reservations/reservations_table", reservations: @place.reservations %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              places_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_place_path(@place), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              place_path(@place),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>